sonar optional 3 (husky prepush file)

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -16,16 +16,20 @@ if [ $? -ne 0 ]; then
   exit 1
 fi
 
-# Run SonarQube only when pushing to the main branch
+# Run SonarQube only when pushing to the main branch and if sonar is runing
 if [ "$current_branch" = "$MAIN_BRANCH" ]; then
-  echo "Running SonarQube analysis for main branch..."
-  npm run sonar
-  if [ $? -ne 0 ]; then
-    echo "SonarQube analysis failed. Please address issues before pushing to main."
-    exit 1
-  fi
+ if nc -z localhost 9000; then
+   echo "Running SonarQube analysis for main branch..."
+   npm run sonar
+   if [ $? -ne 0 ]; then
+     echo "SonarQube analysis failed - skipping"
+     exit 0
+   fi
+ else
+   echo "SonarQube not running - skipping analysis"
+ fi
 else
-  echo "Skipping SonarQube analysis for branch $current_branch."
+ echo "Skipping SonarQube analysis for branch $current_branch."
 fi
 
 # Allow the push to proceed
